keys:
  - &user_tristan age1tnhdfsww8jlkh3j2f8pxuy5w9rwc5vaths7xmjvfzacp8ht0eers2vzvm9 
  - &host_vm age1kvlttdzseuftsfta29hq58q3s0mejax5mvaa97cees67ma5lj4aq75gfer
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_tristan
        - *host_vm

