{
  hostname,
  pkgs,
  lib,
  username,
  ...
}:
{
  imports = [
    ./boot.nix
    ./hardware.nix
    ./locale.nix
    ./sops.nix
    ../common/base
    ../common/services/openssh.nix
    ../common/services/mysql.nix
    ../common/services/flatpaks.nix
    ../common/services/pipewire.nix
    ../common/services/tailscale.nix
    ../common/services/backup.nix
  ];
}
